apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: RedisCluster
metadata:
  name: {{ include "redisFullName" . }}
spec:
  forProvider:
    name: {{ include "redisFullName" . }}
    description: {{ include "redisDesc" . }}
    environment: PRODUCTION
    folderIdRef:
      name: default
    host:
      - zone: {{ .Values.redisZone }}
    maintenanceWindow:
      - type: WEEKLY
        day: SAT
        hour: 22
    networkIdRef:
      name: default
    securityGroupIdsRefs:
      - name: {{ .Values.securityGroup }}
    resources:
      - diskSize: {{ .Values.diskSize }}
        diskTypeId: {{ .Values.diskTypeId }}
        resourcePresetId: {{ .Values.resourcePresetId }}
    config:
      - version: "{{ .Values.redisVersion }}"
        passwordSecretRef:
          key: password
          name: {{ include "redisFullName" . }}-creds
          namespace: {{ .Values.infraNamespace }}
    tlsEnabled: true
