apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-prod
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/grafana
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - secrets+age-import:///helm-secrets-private-keys/age-key.txt?../../values/grafana-prod.yaml
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
