apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logo-worker
  namespace: argocd
spec:
  destination:
    namespace: logo-apps
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ops/helm/charts/logo_worker
    repoURL: {{ .Values.spec.source.appsRepoURL }}
    targetRevision: {{ .Values.spec.source.appsTargetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/age-key.txt?../../values/logo-worker-prod.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true