apiVersion: resourcemanager.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: default
  annotations:
    crossplane.io/external-name: "b1gtdhu0god37d9v5d0j"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: default
---
kind: Network
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: default
  annotations:
    crossplane.io/external-name: "enp20of6jguj9tn1asjo"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: default
    folderIdRef:
      name: default
---
kind: Subnet
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: default-ru-central1-b
  annotations:
    crossplane.io/external-name: "e2lhthoc1a7netg7hkn6"
spec:
  forProvider:
    networkIdRef:
      name: default
    folderIdRef:
      name: default
    zone: ru-central1-b
    v4CidrBlocks:
      - 10.129.0.0/24  # `yc vpc subnet get default-ru-central1-b`
---
kind: Zone
apiVersion: dns.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: yc-courses
  annotations:
    crossplane.io/external-name: "dnsdsn5s63i3i7jbn0b0"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: yc-courses
    zone: "konstant-anxiety.ru."
    public: true
    folderIdRef:
      name: default
---
kind: ServiceAccount
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: crossplane
  annotations:
    crossplane.io/external-name: "ajeh4fjrr6anhhhfvghd"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: crossplane
    folderIdRef:
      name: default
