apiVersion: v1
kind: Namespace
metadata:
  name: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/crossplane
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/age-key.txt?../../values/crossplane.yaml
  syncPolicy:
    automated: {}
  ignoreDifferences:
    - kind: ClusterRole # ignore in which entities
      group: rbac.authorization.k8s.io # which groups are entities from
      name: crossplane # entity name
      jsonPointers:
        - /rules # path to the field to ignore
