apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-prod
  namespace: argocd
spec:
  destination:
    namespace: infrastructure
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/s3
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/age-key.txt?../../values/s3-prod.yaml
  syncPolicy:
    automated: {}
